config/routes.rb
Rails.application.routes.draw do

  resources :actions
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'home#index'

  namespace :admin do
    devise_for :admin_users, class_name: 'Admin::AdminUser',
                             controllers: { registrations: 'admin/admin_users/registrations',
                                            sessions: 'admin/admin_users/sessions',
                                            passwords: 'admin/admin_users/passwords' },
                             path_names: { sign_in: 'login', sign_out: 'logout',
                                           password: 'secret', confirmation: 'verification',
                                           unlock: 'unblock', registration: 'register',
                                           sign_up: 'sign_up' }

    root to: '/admin/dashboard#index'
    resources :positions

    resources :academic_users do
      member do
        get 'reset_password_form'
        patch 'reset_password'
      end
      collection do
        delete 'destroy_multiple'
      end
    end

    resources :billing_users do
      member do
        get 'reset_password_form'
        patch 'reset_password'
      end
      collection do
        delete 'destroy_multiple'
      end
    end

    resources :roles do
      collection do
        delete 'destroy_multiple'
      end
    end

    resources :facturacion_roles do
      collection do
        delete 'destroy_multiple'
      end
    end

    resources :academico_roles do
      collection do
        delete 'destroy_multiple'
      end
    end

    resources :academico_role_permissions do
      collection do
        delete 'destroy_multiple'
      end
    end

    resources :exchange_rates do
      collection do
        delete 'destroy_multiple'
      end
    end

    resources :branch_offices do
      collection do
        delete 'destroy_multiple'
      end
    end

    resources :parameters do

    end

    resources :billing_transactions do

    end

  end

  namespace :facturacion do
    resources :course_book_registrations do
      collection do
        put :bulk_prices
      end
    end
    resources :daily_processes do
      collection do
        delete 'destroy_multiple'
      end
    end

    resources :companies do
      collection do
        delete 'destroy_multiple'
      end
    end

    resources :company_types do
      collection do
        delete 'destroy_multiple'
      end
    end

    resources :preregistrations do
      collection do
        delete 'destroy_multiple'
      end
    end

    resources :carriers do
      collection do
        delete 'destroy_multiple'
      end
    end

    resources :discounts do
      collection do
        delete 'destroy_multiple'
      end
    end

    resources :tutors do
      collection do
        delete 'destroy_multiple'
      end
    end

    resources :stocks do 
      collection do
        get :multi_transfer
        post :create_transfer
      end
    end

    resources :document_types

    resources :warehouses do
      collection do
        delete 'destroy_multiple'
      end
    end

    resources :cost_centers do
      collection do
        delete 'destroy_multiple'
      end
    end

    resources :books do
      collection do
        delete 'destroy_multiple'
      end
    end

    get 'invoices/search_students', to: 'invoices#search_students'
    get 'invoices/pick_discount', to: 'invoices#read_discount'
    get 'invoices/student_courses', to: 'invoices#student_courses'
    resources :invoices do
      member do
        put :void_document
        get :student
      end
      collection do
        get :detail_values, defaults: {format: 'js'}
        get :remain_values
      end
    end

    resources :receipts do
      member do
        put :void_document
      end
      collection do
        get :student_credit_invoices
      end
    end
    get 'notes/student_invoices/:student_id', to: 'notes#student_invoices'
    get 'notes/invoice_concepts/:invoice_id', to: 'notes#invoice_concepts'

    resources :payment_detail_concepts do
      collection do
        delete "destroy_multiple"
      end
    end

    resources :notes do
    end
    resources :debit_notes do
    end

    resources :accounting_accounts do
      collection do
        delete 'destroy_multiple'
      end
    end

    get 'accounting_accounts/:parent_account/suggest_next_account_number', to: 'accounting_accounts#suggest_next_account_number'
    get 'parameters', to: 'application#parameters'

    devise_for :billing_users, class_name: 'Facturacion::BillingUser',
                               controllers: { registrations: 'facturacion/billing_users/registrations',
                                              sessions: 'facturacion/billing_users/sessions',
                                              passwords: 'facturacion/billing_users/passwords' },
                               path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret',
                                             confirmation: 'verification', unlock: 'unblock',
                                             registration: 'register', sign_up: 'sign_up' }

    root to: '/facturacion/dashboard#index'

  end

  namespace :academico do
    devise_for :academic_users, class_name: 'Academico::AcademicUser',
                                controllers: { registrations: 'academico/academic_users/registrations',
                                               sessions: 'academico/academic_users/sessions',
                                               passwords: 'academico/academic_users/passwords' },
                                path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret',
                                              confirmation: 'verification', unlock: 'unblock',
                                              registration: 'register', sign_up: 'sign_up' }

    root to: '/academico/dashboard#index'

    resources :levels do
      collection do
        delete 'destroy_multiple'
      end
    end

    resources :programs do
      collection do
        delete 'destroy_multiple'
      end
    end

    resources :age_ranges do
      collection do
        delete 'destroy_multiple'
      end
    end

    resources :students do
      collection do
        delete 'destroy_multiple'
      end
    end

    resources :rooms do
      collection do
        delete 'destroy_multiple'
      end
    end

    resources :courses do
      collection do
        delete 'destroy_multiple'
      end
    end
    resources :staffs do
      collection do
        delete 'destroy_multiple'
      end
    end
    get 'level_program/:level_program_id/staff', to: 'staffs#staff_by_level_skill'
    resources :evaluation_schemes do
      collection do
        delete 'destroy_multiple'
      end
    end
    resources :evaluation_parameters do
      collection do
        delete 'destroy_multiple'
      end
    end
    resources :evaluation_parameter_types do
      collection do
        delete 'destroy_multiple'
      end
    end
    resources :course_schedulles do
      collection do
        delete 'destroy_multiple'
      end
    end
    resources :temaries do
      collection do
        delete 'destroy_multiple'
      end
    end
    resources :course_evaluations do
      collection do
        delete 'destroy_multiple'
      end
    end
    resources :course_results do
      collection do
        delete 'destroy_multiple'
      end
    end

    resources :teacher_attendances do
      collection do
        delete 'destroy_multiple'
      end
    end

    resources :course_modalities do
      collection do
        delete 'destroy_multiple'
      end
    end

    resources :time_frames do
      collection do
        delete 'destroy_multiple'
      end
    end

    get 'course/:course_id/evaluation_parameters', to: 'courses#evaluation_parameters_by_course'
    get 'courses/:time_frame_id/time_frame_info', to: 'courses#time_frame_related_info'
    get 'courses/:office_id/lookup_classrooms', to: 'courses#lookup_classrooms'
    # this ugly non restfull path was needed this way
    get 'temaries/:course_id/session', to: 'temaries#session_parameters'
    get 'students/:preregistration_id/preregistration', to: 'students#facturacion_preregistration'
    get 'student_reports/index'
    get 'student_reports_xlsx_file', to: 'student_reports#xlsx_file'
    get 'course_student_reports/index'
    get 'course_student_reports_xlsx_file', to: 'course_student_reports#xlsx_file'
    get 'course_student_reports_pdf_file', to: 'course_student_reports#pdf_file'
    get 'course_quota_reports/index'
    get 'course_quota_reports_xlsx_file', to: 'course_quota_reports#xlsx_file'
    get 'student_ages_reports/index'
  end
end

app/models/academico/academic_user.rb
class Academico::AcademicUser < ApplicationRecord
	mount_uploader :avatar, AvatarUploader

	has_one :admin_academic_user_position, class_name: 'Admin::AcademicUserPosition',
		foreign_key: 'academico_academic_user_id', inverse_of: :academico_academic_user, dependent: :destroy
  has_many :academico_user_roles, class_name: 'Academico::UserRole', foreign_key: :academico_academic_users_id
	has_many :academico_courses, :class_name => "Academico::Course",
		foreign_key: "academico_academic_users_id", :inverse_of => :academico_academic_user
	has_one :academico_staff, class_name: 'Academico::Staff',
		foreign_key: 'academico_academic_users_id', inverse_of: :academico_academic_user, dependent: :destroy
	has_many :academico_temaries, :class_name => "Academico::Temary",
		foreign_key: "created_by", :inverse_of => :academico_academic_user
	# Include default devise modules. Others available are:
	# :confirmable, :lockable, :timeoutable and :omniauthable
	devise :database_authenticatable, :registerable,
	:recoverable, :rememberable, :trackable, :validatable
	include UserModelUtility
	accepts_nested_attributes_for :academico_user_roles, allow_destroy: true
	accepts_nested_attributes_for :admin_academic_user_position, allow_destroy: true
	scope :users_in_staff, -> (position_groups) { joins(admin_academic_user_position: :admin_position)
		.where('admin_positions.admin_module_id = ?', Admin::Module::ACADEMIC)
		.where('admin_academic_user_positions.admin_position_id IN (?)', position_groups)
	}
	scope :unasigned_users, -> () {
		where('academico_academic_users.id NOT IN (?)', Academico::Staff.select(:academico_academic_users_id))
	}
	def display_user_position
		self.admin_academic_user_position.admin_position.display_name if self.admin_academic_user_position.present?
	end

	def display_name_and_position
		self.name + ' - ' + self.display_user_position
	end
end

app/controllers/academico/academic_users/confirmations_controller.rb
class Academico::AcademicUsers::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/academico/academic_users/omniauth_callbacks_controller.rb
class Academico::AcademicUsers::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/academico/academic_users/passwords_controller.rb
class Academico::AcademicUsers::PasswordsController < Devise::PasswordsController
  layout "academico/login_layout"
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/academico/academic_users/registrations_controller.rb
class Academico::AcademicUsers::RegistrationsController < Devise::RegistrationsController
    before_action :set_page_title, :authenticate_facturacion_billing_user!
    helper_method :end_session_path, :current_user, :session_root_path, :edit_eli_user_path
    include Academico::ApplicationHelper
    layout "academico/dashboard_layout"

    # GET /resource/sign_up
    def new
        redirect_to academico_root_path
    end

    # POST /resource
    # def create
    #   super
    # end

    # GET /resource/edit
    # def edit
    #   super
    # end

    # PUT /resource
    def update
       super
    end

    # DELETE /resource
    # def destroy
    #   super
    # end

    # GET /resource/cancel
    # Forces the session data which is usually expired after sign
    # in to be expired now. This is useful if the user wants to
    # cancel oauth signing in/up in the middle of the process,
    # removing all OAuth session data.
    # def cancel
    #   super
    # end

    def controller?(*controller)
        controller.include?(params[:controller])
    end

    def action?(*action)
        action.include?(params[:action])
    end

    private

    def set_page_title
        @page_title = "Academic Management"
    end

    def current_user
        current_academico_academic_user
    end

    def end_session_path
        destroy_academico_academic_user_session_path
    end

    def session_root_path
        academico_root_path
    end

    def edit_eli_user_path
        edit_academico_academic_user_registration_path
    end

    protected

    def after_update_path_for(resource)
        edit_academico_academic_user_registration_path(resource)
    end

    # If you have extra params to permit, append them to the sanitizer.
    # def configure_sign_up_params
    #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
    # end

    # If you have extra params to permit, append them to the sanitizer.
    # def configure_account_update_params
    #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
    # end

    # The path used after sign up.
    # def after_sign_up_path_for(resource)
    #   super(resource)
    # end

    # The path used after sign up for inactive accounts.
    # def after_inactive_sign_up_path_for(resource)
    #   super(resource)
    # end
end

app/controllers/academico/academic_users/sessions_controller.rb
class Academico::AcademicUsers::SessionsController < Devise::SessionsController
  layout "academico/login_layout"
# before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
  def after_sign_in_path_for(resource_or_scope)
    academico_root_path
  end
  def after_sign_out_path_for(resource_or_scope)
    academico_root_path
  end
end

app/controllers/academico/academic_users/unlocks_controller.rb
class Academico::AcademicUsers::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/admin/academic_users_helper.rb
module Admin::AcademicUsersHelper
end

app/views/admin/academic_users/_form.html.erb
<%= form_for(admin_academic_user, :url => url, html: {:class=>"form-horizontal form-label-left", :novalidate => nil}) do |f| %>
  <% if admin_academic_user.errors.any? %>
    <div id="error_explanation" class="alert-danger">
      <h2><%= pluralize(admin_academic_user.errors.count, "error") %> prohibited this admin_academic_user from being saved:</h2>

      <ul>
        <% admin_academic_user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="item form-group">
    <%= f.label :name, :class=>"control-label col-md-3 col-sm-3 col-xs-12" do %>
    Nombre <span class="required">*
    <%end%>
    <div class="col-md-6 col-sm-6 col-xs-12">
      <%= f.text_field :name, :class=>"form-control col-md-7 col-xs-12",:required=>"required" %>
    </div>
  </div>

  <div class="item form-group">
    <%= f.label :email, :class=>"control-label col-md-3 col-sm-3 col-xs-12" do %>
    Correo <span class="required">*
    <%end%>
    <div class="col-md-6 col-sm-6 col-xs-12">
      <%= f.text_field :email, :class=>"form-control col-md-7 col-xs-12",:required=>"required" %>
    </div>
  </div>
  <% if f.object.new_record? %>
    <div class="form-group">
      <%=f.label :password, :class=>"control-label col-md-3 col-sm-3 col-xs-12" do%>
        Nueva Contraseña <i>(dejar en blanco si no deseas actualizarlo)</i>
      <%end%>
      <div class="col-md-6 col-sm-6 col-xs-12">
        <%= f.password_field :password, autocomplete: "off", :class=>"form-control col-md-7 col-xs-12"  %>
        <% if @minimum_password_length %>
        <br />
        <em>Se requieren al menos <%= @minimum_password_length %> caracteres</em>
        <% end %>
      </div>
    </div>
    <div class="form-group">
      <%=f.label :password_confirmation, :class=>"control-label col-md-3 col-sm-3 col-xs-12" do%>
        Confirmacion de Contraseña
      <%end%>
      <div class="col-md-6 col-sm-6 col-xs-12">
        <%= f.password_field :password_confirmation, autocomplete: "off", :class=>"form-control col-md-7 col-xs-12"  %>
      </div>
    </div>
  <% end %>
  <div class="form-group">
    <%=f.label :admin_position_id, :class=>"control-label col-md-3 col-sm-3 col-xs-12" do%>
      Cargo
    <%end%>
    <div class="col-md-6 col-sm-6 col-xs-12">
      <%= f.fields_for :admin_academic_user_position do |fp| %>
        <%= fp.hidden_field :academico_academic_user_id %>
        <%= fp.collection_select :admin_position_id, @admin_positions, :id, :name, { include_blank: true}, {:class=>"select2_single form-control", :tabindex=>"-1", :onchange => "cleanHasOneOption(this.value)"} %>
        <%= fp.hidden_field :_destroy, {value: 1, id: "destroy_academic_user_position", disabled:  :disabled} %>
      <% end %>
    </div>
  </div>
  <div class="item form-group">
    <div><h4>Roles del usuario</h4></div>
    <div class="col-md-9 col-sm-12 col-xs-12">
      <table class="table table-striped">
      <%= f.fields_for :academico_user_roles do |ff| %>
        <tr>
          <td>
            <%= ff.hidden_field :academico_academic_users_id %>
            <%= ff.hidden_field :academico_academico_roles_id %>
            <%= ff.object.academico_role.name %>
          </td>
          <td>
            <%= ff.check_box :_destroy, {:checked => ff.object.persisted?, :class => 'flat'}, '0', '1' %>
          </td>
        </tr>
      <% end %>
      </table>
    </div>
  </div>
  <div class="form-group">
    <div class="col-md-6 col-md-offset-3">
      <%=link_to("Cancelar", admin_academic_users_path, :class=>"btn btn-primary")%>
      <%= submit_tag 'Guardar', class: "btn btn-success", id: "send", data: {disable_with: "Enviando..." } %>
    </div>
  </div>
<% end %>

app/views/admin/academic_users/edit.html.erb
<div class="right_col" role="main">
	<div class="">
		<div class="row">
			<div class="col-md-12 col-sm-12 col-xs-12">
				<div class="x_panel">
					<div class="x_title">
						<h2>Edicion Usuario (<%=@admin_academicuser.email%>)</h2>
						<div class="clearfix"></div>
					</div>
					<div class="x_content">
						<%= render 'form', {admin_academic_user: @admin_academicuser, url: admin_academic_user_path(@admin_academicuser.id)} %>

					</div>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/admin/academic_users/index.html.erb
<div class="right_col" role="main">
  <div class="">

    <div class="clearfix"></div>

    <div class="row">

      <div class="clearfix"></div>

      <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
          <div class="x_title">
            <h2>Usuarios Academicos</h2>
            <ul class="nav navbar-right panel_toolbox panel_button">
              <li>
                <%= link_to(content_tag(:i, nil, :class=>"fa  fa-plus"),new_admin_academic_user_path, :"data-toggle"=>"tooltip", :"data-placement"=>"top", :title=>"", :rel=>"nofollow", :"data-original-title"=>"Nuevo")%>
              </li>
            </ul>
            <div class="clearfix"></div>
          </div>

          <div class="x_content">
            <% if notice.present?%>
              <div class="alert alert-success">
                <a href="#" class="close" data-dismiss="alert" aria-label="close" title="close">×</a>
                <%= notice %>
              </div>
            <% end %>
            <div class="table-responsive">
              <%= form_tag destroy_multiple_admin_academic_users_path, method: :delete, data: { confirm: "Are you sure?"}, :class=>"multi_delete_form" do %>
                <table class="table table-striped jambo_table bulk_action">
                  <thead>
                    <tr class="headings">
                      <th>
                        <input type="checkbox" id="check-all" class="flat">
                      </th>
                      <th class="column-title">Nombre</th>
                      <th class="column-title">E-Mail</th>
                      <th class="column-title">Cargo</th>
                      <th class="column-title no-link last" colspan="4">Action</th>
                      </th>
                      <th class="bulk-actions" colspan="6">
                        <a type="button" id="delete_records" class="antoo submit-form" style="color:#fff; font-weight:500; cursor:pointer">Eliminar ( <span class="action-cnt"> </span> ) <i class="fa fa-trash-o"></i></button>
                      </th>
                    </tr>
                  </thead>

                  <tbody>
                    <% @admin_academicusers.each_with_index do |admin_academic_user, index| %>
                      <tr class="<%= index.odd? ? 'odd' : 'even'%> pointer">
                        <td class="center">
                                    <input type="checkbox" name="admin_academic_user_ids[]" id="admin_academic_user_id_<%=admin_academic_user.id%>" value="<%=admin_academic_user.id%>" class="flat deletable">
                              </td>

                        <td><%= admin_academic_user.name %></td>
                        <td><%= admin_academic_user.email %></td>
                        <td><%= admin_academic_user.display_user_position %></td>

                        <td class=" last"><%= link_to content_tag(:i,nil,:class=>"fa fa-search"), admin_academic_user_path(admin_academic_user.id) %></td>
                        <td class=" last"><%= link_to content_tag(:i,nil,:class=>"fa fa-key"), reset_password_form_admin_academic_user_path(admin_academic_user.id) %></td>
                        <td class=" last"><%= link_to content_tag(:i,nil,:class=>"fa fa-pencil"), edit_admin_academic_user_path(admin_academic_user.id) %></td>
                        <td class=" last"><%= link_to content_tag(:i,nil,:class=>"fa fa-trash-o"), admin_academic_user_path(admin_academic_user.id), method: :delete, data: { confirm: 'Are you sure?' } %></td>
                      </tr>
                    <% end %>
                  </tbody>

                </table>
              <%end%>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/academic_users/new.html.erb
<div class="right_col" role="main">
	<div class="">
		<div class="row">
			<div class="col-md-12 col-sm-12 col-xs-12">
				<div class="x_panel">
					<div class="x_title">
						<h2>Registro de Usuarios Academicos</h2>
						<div class="clearfix"></div>
					</div>
					<div class="x_content">
						<%= render 'form', {admin_academic_user: @admin_academicuser, url: admin_academic_users_path} %>

					</div>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/admin/academic_users/reset_password_form.html.erb
<div class="right_col" role="main">
<div class="">
  <div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
      <div class="x_panel">
        <div class="x_title">
          <h2>Cambiar contraseña</h2>
          <div class="clearfix"></div>
        </div>
        <div class="x_content">
          <%= form_for(@admin_academicuser, :url => { action: 'reset_password'}, html: {:class=>"form-horizontal form-label-left", :novalidate => nil}) do |f| %>
            <% if @admin_academicuser.errors.any? %>
              <div id="error_explanation" class="alert-danger">
                <h2><%= pluralize(@admin_academicuser.errors.count, "error") %> prohibited this @admin_academicuser from being saved:</h2>
          
                <ul>
                  <% @admin_academicuser.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
                  <% end %>
                </ul>
              </div>
            <% end %>

            <div class="form-group">
              <%=f.label :new_password, :class=>"control-label col-md-3 col-sm-3 col-xs-12" do%>
                Nueva Contraseña
              <%end%>
              <div class="col-md-6 col-sm-6 col-xs-12">
                <%= f.password_field :new_password, autocomplete: "off", :class=>"form-control col-md-7 col-xs-12"  %>
                <% if @minimum_password_length %>
                <br />
                <em>Se requieren al menos <%= @minimum_password_length %> caracteres</em>
                <% end %>
              </div>
            </div>
            <div class="form-group">
              <%=f.label :password_confirmation, :class=>"control-label col-md-3 col-sm-3 col-xs-12" do%>
                Confirmacion de Contraseña
              <%end%>
              <div class="col-md-6 col-sm-6 col-xs-12">
                <%= f.password_field :password_confirmation, autocomplete: "off", :class=>"form-control col-md-7 col-xs-12"  %>
              </div>
            </div>
          
            <div class="form-group">
              <div class="col-md-6 col-md-offset-3">
                <%=link_to("Cancelar", @admin_academicusers_path, :class=>"btn btn-primary")%>
                <%= submit_tag 'Guardar', class: "btn btn-success", id: "send", data: {disable_with: "Enviando..." } %>
              </div>
            </div>
          <% end %>

        </div>
      </div>
    </div>
  </div>
</div>
</div>

app/views/admin/academic_users/show.html.erb
<div class="right_col" role="main" style="min-height: 1053px;">
  <div class="">
    <div class="page-title">
      <div class="title_left">
        <h3><%=@admin_academicuser.name %></h3>
      </div>
    </div>

    <div class="clearfix"></div>

    <div class="row">
      <div class="col-md-12">

        <div class="x_panel">

          <div class="x_content">
            <% if notice.present?%>
              <div class="alert alert-success">
                <a href="#" class="close" data-dismiss="alert" aria-label="close" title="close">×</a>
                <%= notice %>
              </div>
            <% end %>
            <div class="col-md-8 col-lg-8 col-sm-7">
              <!-- blockquote -->
              <blockquote>

                <h2>Nombre:</h2>
                <h4><%= @admin_academicuser.name %></h4>

                <h2>Correo:</h2>
                <h4><%= @admin_academicuser.email %></h4>

                <h2>Ultimo Inicio de Sesion:</h2>
                <h4><%= @admin_academicuser.last_sign_in_at %></h4>

              </blockquote>

              <blockquote class="blockquote-reverse">

                  <%= link_to 'Editar', edit_admin_academic_user_path(@admin_academicuser), :class=>"btn btn-primary" %>
                  <%= link_to 'Atrás', admin_academic_users_path, :class=>"btn btn-success" %>

              </blockquote>
            </div>

          </div>
        </div>
      </div>
    </div>
  </div>
</div>