config/routes.rb
Rails.application.routes.draw do

  resources :actions
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'home#index'

  namespace :admin do
    devise_for :admin_users, class_name: 'Admin::AdminUser',
                             controllers: { registrations: 'admin/admin_users/registrations',
                                            sessions: 'admin/admin_users/sessions',
                                            passwords: 'admin/admin_users/passwords' },
                             path_names: { sign_in: 'login', sign_out: 'logout',
                                           password: 'secret', confirmation: 'verification',
                                           unlock: 'unblock', registration: 'register',
                                           sign_up: 'sign_up' }

    root to: '/admin/dashboard#index'
    resources :positions

    resources :academic_users do
      member do
        get 'reset_password_form'
        patch 'reset_password'
      end
      collection do
        delete 'destroy_multiple'
      end
    end

    resources :billing_users do
      member do
        get 'reset_password_form'
        patch 'reset_password'
      end
      collection do
        delete 'destroy_multiple'
      end
    end

    resources :roles do
      collection do
        delete 'destroy_multiple'
      end
    end

    resources :facturacion_roles do
      collection do
        delete 'destroy_multiple'
      end
    end

    resources :academico_roles do
      collection do
        delete 'destroy_multiple'
      end
    end

    resources :academico_role_permissions do
      collection do
        delete 'destroy_multiple'
      end
    end

    resources :exchange_rates do
      collection do
        delete 'destroy_multiple'
      end
    end

    resources :branch_offices do
      collection do
        delete 'destroy_multiple'
      end
    end

    resources :parameters do

    end

    resources :billing_transactions do

    end

  end

  namespace :facturacion do
    resources :course_book_registrations do
      collection do
        put :bulk_prices
      end
    end
    resources :daily_processes do
      collection do
        delete 'destroy_multiple'
      end
    end

    resources :companies do
      collection do
        delete 'destroy_multiple'
      end
    end

    resources :company_types do
      collection do
        delete 'destroy_multiple'
      end
    end

    resources :preregistrations do
      collection do
        delete 'destroy_multiple'
      end
    end

    resources :carriers do
      collection do
        delete 'destroy_multiple'
      end
    end

    resources :discounts do
      collection do
        delete 'destroy_multiple'
      end
    end

    resources :tutors do
      collection do
        delete 'destroy_multiple'
      end
    end

    resources :stocks do 
      collection do
        get :multi_transfer
        post :create_transfer
      end
    end

    resources :document_types

    resources :warehouses do
      collection do
        delete 'destroy_multiple'
      end
    end

    resources :cost_centers do
      collection do
        delete 'destroy_multiple'
      end
    end

    resources :books do
      collection do
        delete 'destroy_multiple'
      end
    end

    get 'invoices/search_students', to: 'invoices#search_students'
    get 'invoices/pick_discount', to: 'invoices#read_discount'
    get 'invoices/student_courses', to: 'invoices#student_courses'
    resources :invoices do
      member do
        put :void_document
        get :student
      end
      collection do
        get :detail_values, defaults: {format: 'js'}
        get :remain_values
      end
    end

    resources :receipts do
      member do
        put :void_document
      end
      collection do
        get :student_credit_invoices
      end
    end
    get 'notes/student_invoices/:student_id', to: 'notes#student_invoices'
    get 'notes/invoice_concepts/:invoice_id', to: 'notes#invoice_concepts'

    resources :payment_detail_concepts do
      collection do
        delete "destroy_multiple"
      end
    end

    resources :notes do
    end
    resources :debit_notes do
    end

    resources :accounting_accounts do
      collection do
        delete 'destroy_multiple'
      end
    end

    get 'accounting_accounts/:parent_account/suggest_next_account_number', to: 'accounting_accounts#suggest_next_account_number'
    get 'parameters', to: 'application#parameters'

    devise_for :billing_users, class_name: 'Facturacion::BillingUser',
                               controllers: { registrations: 'facturacion/billing_users/registrations',
                                              sessions: 'facturacion/billing_users/sessions',
                                              passwords: 'facturacion/billing_users/passwords' },
                               path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret',
                                             confirmation: 'verification', unlock: 'unblock',
                                             registration: 'register', sign_up: 'sign_up' }

    root to: '/facturacion/dashboard#index'

  end

  namespace :academico do
    devise_for :academic_users, class_name: 'Academico::AcademicUser',
                                controllers: { registrations: 'academico/academic_users/registrations',
                                               sessions: 'academico/academic_users/sessions',
                                               passwords: 'academico/academic_users/passwords' },
                                path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret',
                                              confirmation: 'verification', unlock: 'unblock',
                                              registration: 'register', sign_up: 'sign_up' }

    root to: '/academico/dashboard#index'

    resources :levels do
      collection do
        delete 'destroy_multiple'
      end
    end

    resources :programs do
      collection do
        delete 'destroy_multiple'
      end
    end

    resources :age_ranges do
      collection do
        delete 'destroy_multiple'
      end
    end

    resources :students do
      collection do
        delete 'destroy_multiple'
      end
    end

    resources :rooms do
      collection do
        delete 'destroy_multiple'
      end
    end

    resources :courses do
      collection do
        delete 'destroy_multiple'
      end
    end
    resources :staffs do
      collection do
        delete 'destroy_multiple'
      end
    end
    get 'level_program/:level_program_id/staff', to: 'staffs#staff_by_level_skill'
    resources :evaluation_schemes do
      collection do
        delete 'destroy_multiple'
      end
    end
    resources :evaluation_parameters do
      collection do
        delete 'destroy_multiple'
      end
    end
    resources :evaluation_parameter_types do
      collection do
        delete 'destroy_multiple'
      end
    end
    resources :course_schedulles do
      collection do
        delete 'destroy_multiple'
      end
    end
    resources :temaries do
      collection do
        delete 'destroy_multiple'
      end
    end
    resources :course_evaluations do
      collection do
        delete 'destroy_multiple'
      end
    end
    resources :course_results do
      collection do
        delete 'destroy_multiple'
      end
    end

    resources :teacher_attendances do
      collection do
        delete 'destroy_multiple'
      end
    end

    resources :course_modalities do
      collection do
        delete 'destroy_multiple'
      end
    end

    resources :time_frames do
      collection do
        delete 'destroy_multiple'
      end
    end

    get 'course/:course_id/evaluation_parameters', to: 'courses#evaluation_parameters_by_course'
    get 'courses/:time_frame_id/time_frame_info', to: 'courses#time_frame_related_info'
    get 'courses/:office_id/lookup_classrooms', to: 'courses#lookup_classrooms'
    # this ugly non restfull path was needed this way
    get 'temaries/:course_id/session', to: 'temaries#session_parameters'
    get 'students/:preregistration_id/preregistration', to: 'students#facturacion_preregistration'
    get 'student_reports/index'
    get 'student_reports_xlsx_file', to: 'student_reports#xlsx_file'
    get 'course_student_reports/index'
    get 'course_student_reports_xlsx_file', to: 'course_student_reports#xlsx_file'
    get 'course_student_reports_pdf_file', to: 'course_student_reports#pdf_file'
    get 'course_quota_reports/index'
    get 'course_quota_reports_xlsx_file', to: 'course_quota_reports#xlsx_file'
    get 'student_ages_reports/index'
  end
end

app/models/facturacion.rb
module Facturacion
  def self.table_name_prefix
    'facturacion_'
  end
end

app/models/facturacion/account_to_record.rb
class Facturacion::AccountToRecord < ApplicationRecord
  has_many :facturacion_accounting_accounts, inverse_of: :facturacion_account_to_record,
   class_name: 'Facturacion::AccountingAccount', foreign_key: :facturacion_account_to_records_id
end

app/models/facturacion/account_type.rb
class Facturacion::AccountType < ApplicationRecord
  has_many :facturacion_accounting_accounts, inverse_of: :facturacion_account_type,
   class_name: 'Facturacion::AccountingAccount', foreign_key: :facturacion_account_types_id
end

app/models/facturacion/accounting_account.rb
class Facturacion::AccountingAccount < ApplicationRecord
  include Filterable
  belongs_to :facturacion_account_to_record, class_name: 'Facturacion::AccountToRecord',
    inverse_of: :facturacion_accounting_accounts, foreign_key: :facturacion_account_to_records_id
  belongs_to :facturacion_account_type, class_name: 'Facturacion::AccountType',
    inverse_of: :facturacion_accounting_accounts, foreign_key: :facturacion_account_types_id
  belongs_to :facturacion_accounting_account_category, class_name: 'Facturacion::AccountingAccountCategory',
    inverse_of: :facturacion_accounting_accounts, foreign_key: :facturacion_accounting_account_categories_id
  belongs_to :facturacion_parent_account, class_name: 'Facturacion::AccountingAccount',
    foreign_key: :parent_account

  scope :activo, -> { where(facturacion_accounting_account_categories_id: Facturacion::AccountingAccountCategory::ACTIVO) }
  scope :pasivo, -> { where(facturacion_accounting_account_categories_id: Facturacion::AccountingAccountCategory::PASIVO) }
  scope :capital, -> { where(facturacion_accounting_account_categories_id: Facturacion::AccountingAccountCategory::CAPITAL) }
  scope :egreso, -> { where(facturacion_accounting_account_categories_id: Facturacion::AccountingAccountCategory::EGRESO) }
  scope :ingreso, -> { where(facturacion_accounting_account_categories_id: Facturacion::AccountingAccountCategory::INGRESO) }
  scope :disableds, -> { where(is_disabled: true) }
  scope :enableds, -> { where(is_disabled: false) }

  scope :account_category_eq, -> (category_id) { where('facturacion_accounting_account_categories_id = ?', category_id)}
  scope :parent_account_eq, -> (account_id) { where('parent_account = ?', account_id)}
  scope :account_type_eq, -> (type_id) { where('facturacion_account_types_id = ?', type_id)}
  scope :account_number_like, -> (account_number) { where('account_number ilike ?', "%#{account_number}%")}
  scope :name_like, -> (account_name) { where('name ilike ?', "%#{account_name}%")}
  scope :status_eq, -> (status) { where('is_disabled = ?', status == 'true')}
  default_scope { enableds.order(:account_number) }

  def status
    self.is_disabled ? 'Inactiva' : 'Activa'
  end

  def hijas(cuentas_padre, recursive = false)
    cuentas = CuentaContable.where(cuenta_padre_id: self.cuenta_contable_id)

    return [self] if self.tipo_cuenta_id == TipoCuenta::DETALLE

    if recursive
      cuentas.map do |c|
        if c.tipo_cuenta_id == TipoCuenta::MAYOR
          c.hijas(nil, true)
        else
          c
        end
      end.flatten
    else
      CuentaContable.where(cuenta_padre_id: self.cuenta_contable_id)
                    .where('cuenta_contable_id not in (?)', cuentas_padre).order(:numero_cuenta)
    end
  end

  def display_name
    "#{self.account_number} / #{self.name}"
  end

  def self.suggest_child_number(parent_account_id)
    return "" if parent_account_id.blank?
    parent_account_obj = self.find(parent_account_id)
    account_digits = 4
    remove_pattern = "\-0{#{account_digits},}"
    if parent_account_obj.present?
      account = ""
      int_part = 0
      first_number = nil
      counter = 0
      regex = Regexp.compile(remove_pattern)

      parent_account_number = parent_account_obj.account_number.gsub(regex, "")
      children_accounts = self.where(parent_account: parent_account_id).order("account_number ASC")
      children_accounts.each do |child|
        account = child.account_number.gsub(regex, "")
        position = account.index(parent_account_number)
        if position.nil?
          next
        end

        position += parent_account_number.size
        left_over = account.slice(position, account.size)
        if left_over.size == 0
          next
        end

          # Iterate children and test if there are holes in between to return the next hole if any otherwise the biggest number
        if (matched_expr = /^\-\d+/.match(left_over)).present?
          int_part = matched_expr.to_s.gsub(/^\-/, "").try(:to_i)
          if first_number.nil?
            first_number = int_part
          end
          if first_number + counter < int_part
            return "#{parent_account_number}-#{self.format_number(first_number + counter, account_digits)}"
          end
          counter+=1
        end
      end
      "#{parent_account_number}-#{self.format_number(counter + 1, account_digits)}"
    end
  end

  def self.format_number(number, digits)
    if number.is_a? Integer
      number_as_str = number.to_s
      if number_as_str.size <= digits
        return '0'*(digits - number_as_str.size) + number_as_str
      end
    end
  end
end

app/models/facturacion/accounting_account_category.rb
class Facturacion::AccountingAccountCategory < ApplicationRecord
  has_many :facturacion_accounting_accounts, inverse_of: :facturacion_accounting_account_category,
   class_name: 'Facturacion::AccountingAccount', foreign_key: :facturacion_accounting_account_categories_id

  ACTIVO = 1
  PASIVO = 2
  CAPITAL = 3
  EGRESO = 4
  INGRESO = 5
end

app/models/facturacion/billing_user.rb
class Facturacion::BillingUser < ApplicationRecord
	mount_uploader :avatar, AvatarUploader
	has_many :facturacion_user_roles, class_name: 'Facturacion::UserRole', foreign_key: :facturacion_billing_user_id
	has_one :admin_billing_user_position, :class_name => "Admin::BillingUserPosition",
		foreign_key: "facturacion_billing_user_id", :inverse_of => :facturacion_billing_user
	# Include default devise modules. Others available are:
	# :confirmable, :lockable, :timeoutable and :omniauthable
	devise :database_authenticatable, :registerable,
	:recoverable, :rememberable, :trackable, :validatable
	include UserModelUtility
	accepts_nested_attributes_for :facturacion_user_roles, allow_destroy: true

	belongs_to :admin_branch_office, class_name: 'Admin::BranchOffice'

	def display_name
		email
	end

  def self.current
    Thread.current[:billing_user]
  end

  def self.current=(user)
    Thread.current[:billing_user] = user
  end
end

app/models/facturacion/book.rb
class Facturacion::Book < ApplicationRecord
    before_destroy :check_for_level_program_book, :check_for_stock

    has_many :academico_level_program_books, :class_name => "Academico::LevelProgramBook", 
        foreign_key: "facturacion_book_id", :inverse_of => :facturacion_book

    has_many :facturacion_stocks, :class_name => "Facturacion::Stock", 
        foreign_key: "facturacion_book_id", :inverse_of => :facturacion_book

    has_many :facturacion_invoice_detail_books, :class_name => "Facturacion::InvoiceDetailBook", 
        foreign_key: "facturacion_book_id", :inverse_of => :facturacion_book

  belongs_to :academico_level, class_name: 'Academico::Level', foreign_key: "academico_level_id",
             inverse_of: :facturacion_book
  belongs_to :academico_program, class_name: 'Academico::Program', foreign_key: "academico_program_id",
             inverse_of: :facturacion_book

    include AvoidDestroyReferencesUtility 

    validates_presence_of :name, :description, :min_stock, :price
    validates_uniqueness_of :name

    def display_name
        name
    end

  def self.search_book_for_payment_detail_concept(is_book, is_other_item, course_id)

    if is_book
        course = Facturacion::CourseBookRegistration.where(academico_course_id: course_id).first
        course.facturacion_books
        
    elsif is_other_item
        books = Facturacion::CourseBookRegistration.joins(:facturacion_books).pluck(:facturacion_book_id).uniq
        Facturacion::Book.where("id not in (?)", books)
    end
  end

    private
    def check_for_level_program_book
        check_for_relation(academico_level_program_books, "Nivel")
    end

    def check_for_stock
        check_for_relation(facturacion_stocks, "Stock")
    end
end

app/models/facturacion/company_type.rb
class Facturacion::CompanyType < ApplicationRecord
	before_destroy :check_for_companies
	has_many :facturacion_companies, :class_name => "Facturacion::Company", 
		foreign_key: "facturacion_company_type_id", inverse_of: :facturacion_company_type
	validates_presence_of :name, :description
	validates_uniqueness_of :name
	include AvoidDestroyReferencesUtility #Validacion en concern para relaciones con modelo preregistro, bloquea el destroy del registro
	
	def display_name
		name
	end
	
	private
	def check_for_companies
		check_for_relation(facturacion_companies, "Empresa")
	end
end

app/views/layouts/facturacion/dashboard_layout.html.erb
<!DOCTYPE html>
<html>
<head>
	<title><%=@page_title%></title>
	<%= csrf_meta_tags %>

	<%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
	<!-- jVectorMap -->
	<script src="/assets/maps/jquery-jvectormap-world-mill-en.js"></script>
	<script src="/assets/maps/jquery-jvectormap-us-aea-en.js"></script>
	<script src="/assets/maps/gdp-data.js"></script>
	<%= favicon_link_tag 'favicon.ico', type: 'image/png' %>
	<%= favicon_link_tag 'favicon.ico'%>
	<meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, user-scalable=yes"/>
	<!-- fuente lato -->
  <link href="https://fonts.googleapis.com/css?family=Lato:300,300i,400,400i,700,700i,900,900i" rel="stylesheet">
  <!-- css -->
  <link rel="stylesheet" type="text/css" href="/assets/default.css" />
  <!-- Smartphones (portrait 240 - 320) -->
  <link rel="stylesheet" href="/assets/s240_base.css" type="text/css" media="only screen and (min-width : 240px)" />
  <link rel="stylesheet" href="/assets/s240_body.css" type="text/css" media="only screen and (min-width : 240px)" />
  <link rel="stylesheet" href="/assets/s240_update.css" type="text/css" media="only screen and (min-width : 240px)" />
</head>

<body class="nav-md footer_fixed">
	<div class="container body">
		<div class="main_container">
			<div class="col-md-3 left_col menu_fixed">
				<div class="left_col scroll-view">
					<div class="navbar nav_title" style="border: 0;">
						<a href="<%=session_root_path%>" class="site_title"><i class="fa fa-university"></i> <span>ELI Billing</span></a>
					</div>

					<div class="clearfix"></div>

					<!-- menu profile quick info -->
					<div class="profile clearfix">
						<div class="profile_pic">
							<%=image_tag(current_user.image_source("avatar"), :class=>"img-circle profile_img",	 :alt=>"#{current_user.name.to_s}", :title=>"#{current_user.name.to_s}")%>
						</div>
						<div class="profile_info">
							<span>Bienvenido,</span>
							<h2><%=current_user.name.to_s%></h2>
						</div>
					</div>
					<!-- /menu profile quick info -->

					<br />
					<!-- sidebar menu -->
					<div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
						<div class="menu_section">
							<ul class="nav side-menu">
								<li class="current-page"><a href="<%=session_root_path%>"><i class="fa fa-home"></i> Dashboard</a>
								</li>
								<li><a><i class="fa fa-book"></i>Pre Registro <span class="fa fa-chevron-down"></span></a>
									<ul class="nav child_menu">
										<li><%=link_to "Pre-registros", facturacion_preregistrations_path%></li>
										<li><%=link_to "Tutores", facturacion_tutors_path%></li>
										<li><%=link_to "Empresas", facturacion_companies_path%></li>
										<li><%=link_to "Tipos de empresa", facturacion_company_types_path%></li>
										<li><%=link_to "Transportistas", facturacion_carriers_path%></li>
										<li><%=link_to "Descuentos", facturacion_discounts_path%></li>
									</ul>
								</li>
								<li><a><i class="fa fa-bar-chart-o"></i>Facturacion <span class="fa fa-chevron-down"></span></a>
									<ul class="nav child_menu">
										<li><%=link_to "Facturas", facturacion_invoices_path%></li>
										<li><%=link_to "Recibos", facturacion_receipts_path%></li>
									</ul>
								</li>
								<li><a><i class="fa fa-book"></i> Notas <span class="fa fa-chevron-down"></span></a>
									<ul class="nav child_menu">
										<li><%=link_to "Notas de crédito", facturacion_notes_path%></li>
										<li><%=link_to "Notas de débito", facturacion_debit_notes_path%></li>
									</ul>
								</li>
								<li><a><i class="fa fa-archive"></i>Inventario <span class="fa fa-chevron-down"></span></a>
									<ul class="nav child_menu">
										<li><%=link_to "Kardex", facturacion_stocks_path%></li>
										<li><%=link_to "Libros", facturacion_books_path%></li>
										<li><%=link_to "Reportes", "#"%></li>
									</ul>
								</li>
								<li><a><i class="fa fa-cubes"></i>Bodegas <span class="fa fa-chevron-down"></span></a>
									<ul class="nav child_menu">
										<li><%=link_to "Bodega", facturacion_warehouses_path%></li>
										<li><%=link_to "Centros de Costo", facturacion_cost_centers_path%></li>
										<li><%=link_to "Transferencias", multi_transfer_facturacion_stocks_path%></li>
									</ul>
								</li>
								<!--<li><a><i class="fa fa-line-chart"></i>Comprobantes <span class="fa fa-chevron-down"></span></a>
									<ul class="nav child_menu">
										<li><%=link_to "Generar", "#"%></li>
									</ul>
								</li>-->
								<li><a><i class="fa fa-wrench"></i>Utilidades <span class="fa fa-chevron-down"></span></a>
									<ul class="nav child_menu">
										<li><%=link_to "Conceptos de pago", facturacion_payment_detail_concepts_path%></li>
										<li><%=link_to "Precios Libro - Matricula  / curso", facturacion_course_book_registrations_path%></li>
										<li><%=link_to "Catálogo de cuentas", facturacion_accounting_accounts_path %></li>
										<li><%=link_to "Cierre Diario", facturacion_daily_processes_path %></li>
									</ul>
								</li>
							</ul>
						</div>

					</div>
					<!-- /sidebar menu -->

					<!-- /menu footer buttons -->
					<%=footer_menu%>
					<!-- /menu footer buttons -->
				</div>
			</div>

			<!-- top navigation -->
			<%=top_nav_menu%>
			<!-- /top navigation -->

			<!-- page content -->
			<%=yield%>
			<!-- /page content -->
			<!-- footer content -->
			<%=render "shared/footer"%>
			<!-- /footer content -->
		</div>
	</div>
	<%=render "shared/spinner"%>
</body>
</html>

app/views/layouts/facturacion/login_layout.html.erb
<!DOCTYPE html>
<html class="login">
<head>
  <title><%=@page_title%></title>
  <%= csrf_meta_tags %>

  <%= favicon_link_tag 'favicon.ico', type: 'image/png' %>
  <%= favicon_link_tag 'favicon.ico'%>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, user-scalable=yes"/>
  
  <!-- jquery librery -->

  <!-- google font -->
    <!-- fuente lato -->
    <link href="https://fonts.googleapis.com/css?family=Lato:300,300i,400,400i,700,700i,900,900i" rel="stylesheet">

  <!-- screens -->
    <!-- css -->
    <link rel="stylesheet" type="text/css" href="/assets/default.css" />
    <!-- Smartphones (portrait 240 - 320) -->
    <link rel="stylesheet" href="/assets/s240_base.css" type="text/css" media="only screen and (min-width : 240px)" />
    <link rel="stylesheet" href="/assets/s240_body.css" type="text/css" media="only screen and (min-width : 240px)" />
    <link rel="stylesheet" href="/assets/s240_update.css" type="text/css" media="only screen and (min-width : 240px)" />
    <link rel="stylesheet" href="/assets/s240_login.css" type="text/css" media="only screen and (min-width : 240px)" />


</head>
<body class="login">
  
  <div class="container_login g_max_30w_s700 right_block_s700 relative z1">
    <div class="midd_container bck_cover bck_panel_login">
      <div class="midd_cell">
        
        <div class="login_wrap text-center max_w_25 mar_auto">
          
          <div class="logo_eli mar_auto left_block_s700">
            <img src="/assets/logo_eli.png" alt="" class="w100p">
          </div>

          <br>
          <div class="title_login bolder">
            Bienvenido a <span>ELI</span>
          </div>
          <div class="row_lm italic">
            <%=devise_error_messages!%>
          </div>
          
          <!-- container -->
          <div>
            <br>
            <%= yield%>
          </div>

          <!-- logo americano -->
          <div class="only_900 bottom_logo text-center max_w_25 mar_auto w70p">
            <div class="relative icon logo_am w100p h5 mar_auto "></div>
          </div>
          <!-- footer min height -->
          <div class="min_height_footer footer_index">
            Copyright © 2018 American Nicaraguan School. All rights reserved. 
          </div>
        </div>

      </div>
    </div>
    
    
  </div>

  <!-- bottom -->
  <div class="pad_r_30_s700 relative_s700 container_complement_s700 wh100p_s700 absolute_default_s700 fixed_min_500">
    <div class="relative_s700 wh100p_s700 bck_cover">
      <div class="only_900 bs100">
        <div class="midd_container h100p">
          <div class="midd_cell">
            <div class="c_white bolder login_wrap max_w_40 mar_auto ">
              <div class="uppercase text-center fs_13">
                the best of your life begins at <span class="c_yellow">ELI</span>
              </div>
              <br>
              <div class="fs_12 row_lm">
                <div class="text-center">
                  Con más de <span class="c_yellow">40 años</span> formando bilingües,<br>Pioneros en la enseñanza del idioma inglés a nivel nacional
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="footer_login text-center z2">
        Copyright © 2018 American Nicaraguan School. All rights reserved. 
      </div>
    </div>
  </div>
</body>
</html>