config/routes.rb
Rails.application.routes.draw do

  resources :actions
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'home#index'

  namespace :admin do
    devise_for :admin_users, class_name: 'Admin::AdminUser',
                             controllers: { registrations: 'admin/admin_users/registrations',
                                            sessions: 'admin/admin_users/sessions',
                                            passwords: 'admin/admin_users/passwords' },
                             path_names: { sign_in: 'login', sign_out: 'logout',
                                           password: 'secret', confirmation: 'verification',
                                           unlock: 'unblock', registration: 'register',
                                           sign_up: 'sign_up' }

    root to: '/admin/dashboard#index'
    resources :positions

    resources :academic_users do
      member do
        get 'reset_password_form'
        patch 'reset_password'
      end
      collection do
        delete 'destroy_multiple'
      end
    end

    resources :billing_users do
      member do
        get 'reset_password_form'
        patch 'reset_password'
      end
      collection do
        delete 'destroy_multiple'
      end
    end

    resources :roles do
      collection do
        delete 'destroy_multiple'
      end
    end

    resources :facturacion_roles do
      collection do
        delete 'destroy_multiple'
      end
    end

    resources :academico_roles do
      collection do
        delete 'destroy_multiple'
      end
    end

    resources :academico_role_permissions do
      collection do
        delete 'destroy_multiple'
      end
    end

    resources :exchange_rates do
      collection do
        delete 'destroy_multiple'
      end
    end

    resources :branch_offices do
      collection do
        delete 'destroy_multiple'
      end
    end

    resources :parameters do

    end

    resources :billing_transactions do

    end

  end

  namespace :facturacion do
    resources :course_book_registrations do
      collection do
        put :bulk_prices
      end
    end
    resources :daily_processes do
      collection do
        delete 'destroy_multiple'
      end
    end

    resources :companies do
      collection do
        delete 'destroy_multiple'
      end
    end

    resources :company_types do
      collection do
        delete 'destroy_multiple'
      end
    end

    resources :preregistrations do
      collection do
        delete 'destroy_multiple'
      end
    end

    resources :carriers do
      collection do
        delete 'destroy_multiple'
      end
    end

    resources :discounts do
      collection do
        delete 'destroy_multiple'
      end
    end

    resources :tutors do
      collection do
        delete 'destroy_multiple'
      end
    end

    resources :stocks do 
      collection do
        get :multi_transfer
        post :create_transfer
      end
    end

    resources :document_types

    resources :warehouses do
      collection do
        delete 'destroy_multiple'
      end
    end

    resources :cost_centers do
      collection do
        delete 'destroy_multiple'
      end
    end

    resources :books do
      collection do
        delete 'destroy_multiple'
      end
    end

    get 'invoices/search_students', to: 'invoices#search_students'
    get 'invoices/pick_discount', to: 'invoices#read_discount'
    get 'invoices/student_courses', to: 'invoices#student_courses'
    resources :invoices do
      member do
        put :void_document
        get :student
      end
      collection do
        get :detail_values, defaults: {format: 'js'}
        get :remain_values
      end
    end

    resources :receipts do
      member do
        put :void_document
      end
      collection do
        get :student_credit_invoices
      end
    end
    get 'notes/student_invoices/:student_id', to: 'notes#student_invoices'
    get 'notes/invoice_concepts/:invoice_id', to: 'notes#invoice_concepts'

    resources :payment_detail_concepts do
      collection do
        delete "destroy_multiple"
      end
    end

    resources :notes do
    end
    resources :debit_notes do
    end

    resources :accounting_accounts do
      collection do
        delete 'destroy_multiple'
      end
    end

    get 'accounting_accounts/:parent_account/suggest_next_account_number', to: 'accounting_accounts#suggest_next_account_number'
    get 'parameters', to: 'application#parameters'

    devise_for :billing_users, class_name: 'Facturacion::BillingUser',
                               controllers: { registrations: 'facturacion/billing_users/registrations',
                                              sessions: 'facturacion/billing_users/sessions',
                                              passwords: 'facturacion/billing_users/passwords' },
                               path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret',
                                             confirmation: 'verification', unlock: 'unblock',
                                             registration: 'register', sign_up: 'sign_up' }

    root to: '/facturacion/dashboard#index'

  end

  namespace :academico do
    devise_for :academic_users, class_name: 'Academico::AcademicUser',
                                controllers: { registrations: 'academico/academic_users/registrations',
                                               sessions: 'academico/academic_users/sessions',
                                               passwords: 'academico/academic_users/passwords' },
                                path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret',
                                              confirmation: 'verification', unlock: 'unblock',
                                              registration: 'register', sign_up: 'sign_up' }

    root to: '/academico/dashboard#index'

    resources :levels do
      collection do
        delete 'destroy_multiple'
      end
    end

    resources :programs do
      collection do
        delete 'destroy_multiple'
      end
    end

    resources :age_ranges do
      collection do
        delete 'destroy_multiple'
      end
    end

    resources :students do
      collection do
        delete 'destroy_multiple'
      end
    end

    resources :rooms do
      collection do
        delete 'destroy_multiple'
      end
    end

    resources :courses do
      collection do
        delete 'destroy_multiple'
      end
    end
    resources :staffs do
      collection do
        delete 'destroy_multiple'
      end
    end
    get 'level_program/:level_program_id/staff', to: 'staffs#staff_by_level_skill'
    resources :evaluation_schemes do
      collection do
        delete 'destroy_multiple'
      end
    end
    resources :evaluation_parameters do
      collection do
        delete 'destroy_multiple'
      end
    end
    resources :evaluation_parameter_types do
      collection do
        delete 'destroy_multiple'
      end
    end
    resources :course_schedulles do
      collection do
        delete 'destroy_multiple'
      end
    end
    resources :temaries do
      collection do
        delete 'destroy_multiple'
      end
    end
    resources :course_evaluations do
      collection do
        delete 'destroy_multiple'
      end
    end
    resources :course_results do
      collection do
        delete 'destroy_multiple'
      end
    end

    resources :teacher_attendances do
      collection do
        delete 'destroy_multiple'
      end
    end

    resources :course_modalities do
      collection do
        delete 'destroy_multiple'
      end
    end

    resources :time_frames do
      collection do
        delete 'destroy_multiple'
      end
    end

    get 'course/:course_id/evaluation_parameters', to: 'courses#evaluation_parameters_by_course'
    get 'courses/:time_frame_id/time_frame_info', to: 'courses#time_frame_related_info'
    get 'courses/:office_id/lookup_classrooms', to: 'courses#lookup_classrooms'
    # this ugly non restfull path was needed this way
    get 'temaries/:course_id/session', to: 'temaries#session_parameters'
    get 'students/:preregistration_id/preregistration', to: 'students#facturacion_preregistration'
    get 'student_reports/index'
    get 'student_reports_xlsx_file', to: 'student_reports#xlsx_file'
    get 'course_student_reports/index'
    get 'course_student_reports_xlsx_file', to: 'course_student_reports#xlsx_file'
    get 'course_student_reports_pdf_file', to: 'course_student_reports#pdf_file'
    get 'course_quota_reports/index'
    get 'course_quota_reports_xlsx_file', to: 'course_quota_reports#xlsx_file'
    get 'student_ages_reports/index'
  end
end

app/models/academico.rb
module Academico
  def self.table_name_prefix
    'academico_'
  end
end

app/models/academico/academic_user.rb
class Academico::AcademicUser < ApplicationRecord
	mount_uploader :avatar, AvatarUploader

	has_one :admin_academic_user_position, class_name: 'Admin::AcademicUserPosition',
		foreign_key: 'academico_academic_user_id', inverse_of: :academico_academic_user, dependent: :destroy
  has_many :academico_user_roles, class_name: 'Academico::UserRole', foreign_key: :academico_academic_users_id
	has_many :academico_courses, :class_name => "Academico::Course",
		foreign_key: "academico_academic_users_id", :inverse_of => :academico_academic_user
	has_one :academico_staff, class_name: 'Academico::Staff',
		foreign_key: 'academico_academic_users_id', inverse_of: :academico_academic_user, dependent: :destroy
	has_many :academico_temaries, :class_name => "Academico::Temary",
		foreign_key: "created_by", :inverse_of => :academico_academic_user
	# Include default devise modules. Others available are:
	# :confirmable, :lockable, :timeoutable and :omniauthable
	devise :database_authenticatable, :registerable,
	:recoverable, :rememberable, :trackable, :validatable
	include UserModelUtility
	accepts_nested_attributes_for :academico_user_roles, allow_destroy: true
	accepts_nested_attributes_for :admin_academic_user_position, allow_destroy: true
	scope :users_in_staff, -> (position_groups) { joins(admin_academic_user_position: :admin_position)
		.where('admin_positions.admin_module_id = ?', Admin::Module::ACADEMIC)
		.where('admin_academic_user_positions.admin_position_id IN (?)', position_groups)
	}
	scope :unasigned_users, -> () {
		where('academico_academic_users.id NOT IN (?)', Academico::Staff.select(:academico_academic_users_id))
	}
	def display_user_position
		self.admin_academic_user_position.admin_position.display_name if self.admin_academic_user_position.present?
	end

	def display_name_and_position
		self.name + ' - ' + self.display_user_position
	end
end

app/models/academico/academico_ability.rb
class Academico::AcademicoAbility < Ability
  def initialize(user)
    user ||= Academico::AcademicUser.new
    permissions = Admin::AcademicoRolePermission.joins(:academico_role, :academico_user_roles).where('academico_user_roles.academico_academic_users_id = ?', user.id)
    permissions.each do |permission|
      if permission.admin_resource.model == 'Academico::CourseEvaluation'
        if ['show', 'edit', 'update', 'destroy'].include?(permission.action.description)
          can permission.action.description.to_sym, Academico::CourseEvaluation, academico_staffs_id: user.academico_staff.id if user.academico_staff.present?
        else
          can permission.action.description.to_sym, Academico::CourseEvaluation
        end
      elsif permission.admin_resource.model == 'Academico::CourseResult'
        if ['show', 'edit', 'update', 'destroy'].include?(permission.action.description)
          can permission.action.description.to_sym, Academico::CourseResult, academico_staffs_id: user.academico_staff.id if user.academico_staff.present?
        else
          can permission.action.description.to_sym, Academico::CourseResult
        end
      elsif permission.admin_resource.model == 'Academico::Temary'
        if ['edit', 'update', 'destroy'].include?(permission.action.description)
          can permission.action.description.to_sym, Academico::Temary, created_by: user.id
        else
          can permission.action.description.to_sym, Academico::Temary
        end
      elsif permission.admin_resource.model == 'Academico::TeacherAttendance'
        if ['show', 'edit', 'update', 'destroy'].include?(permission.action.description)
          can permission.action.description.to_sym, Academico::TeacherAttendance, created_by: user.academico_staff.id if user.academico_staff.present?
        else
          can permission.action.description.to_sym, Academico::TeacherAttendance
        end
      else
        can permission.action.description.to_sym, permission.admin_resource.model.constantize
      end
    end
  end
end

app/models/academico/academico_role.rb
class Academico::AcademicoRole < ApplicationRecord
  has_many :academico_user_roles, class_name: 'Academico::UserRole', foreign_key: :academico_academico_roles_id

  has_many :academico_role_permissions, inverse_of: :academico_role, class_name: "Admin::AcademicoRolePermission", foreign_key: 'academico_academico_role_id'
  accepts_nested_attributes_for :academico_role_permissions, allow_destroy: true
end

app/models/academico/age_range.rb
class Academico::AgeRange < ApplicationRecord
	before_destroy :check_for_program

	has_many :academico_programs, :class_name => "Academico::Program",
		foreign_key: "academico_age_range_id", :inverse_of => :academico_age_range

	validates_presence_of :name, :min_age, :max_age, :description
	validates_numericality_of :min_age, :max_age
	validates_uniqueness_of :name

	include AvoidDestroyReferencesUtility

	def display_name
		name
	end

  def self.programs_list_by_age_range(age)
    programs = Academico::Program.joins(:academico_age_range).where("academico_age_ranges.min_age <= ? AND academico_age_ranges.max_age >= ?", age, age)
    program_list = programs.to_a
    if program_list.present? && program_list.any? {|program| program.id == Academico::Program::PROGRAM_TEENS}
      program_list << Academico::Program.find(3)
    end
    return program_list
  end

	private
	def check_for_program
		check_for_relation(academico_programs, "Programa")
  end
end

app/models/academico/course_evaluation.rb
class Academico::CourseEvaluation < ApplicationRecord
  belongs_to :academico_course, :class_name => "Academico::Course",
    :inverse_of => :academico_course_evaluations, foreign_key: "academico_courses_id"
  belongs_to :academico_staff, class_name: "Academico::Staff",
    foreign_key: "academico_staffs_id", inverse_of: :academico_course_evaluations
  has_many :academico_session_evaluations, class_name: "Academico::SessionEvaluation",
    foreign_key: "academico_course_evaluations_id", inverse_of: :academico_course_evaluation, dependent: :destroy
  accepts_nested_attributes_for :academico_session_evaluations,
   allow_destroy: true,
   reject_if: :reject_session_if_no_students_records
  def reject_session_if_no_students_records(attributes)
    attributes[:academico_student_evaluations_attributes].count == 0
  end
end

app/models/academico/course_modality.rb
class Academico::CourseModality < ApplicationRecord
  has_many :facturacion_invoices, :class_name => "Facturacion::Invoice",
    foreign_key: "academico_course_modalities_id", :inverse_of => :academico_course_modality
  has_many :academico_courses, :class_name => "Academico::Course",
    foreign_key: "academico_course_modalities_id", :inverse_of => :academico_course_modality
end

app/models/academico/course_result.rb
class Academico::CourseResult < ApplicationRecord
  belongs_to :academico_course, :class_name => "Academico::Course",
    :inverse_of => :academico_course_result, foreign_key: "academico_courses_id"
  has_many :academico_student_results, class_name: 'Academico::StudentResult',
    foreign_key: :academico_course_results_id, inverse_of: :academico_course_result, dependent: :destroy
  belongs_to :coordinator, :class_name => "Academico::Staff",
    :inverse_of => :academico_course_results, foreign_key: "academico_staffs_id"
  accepts_nested_attributes_for :academico_student_results,
   allow_destroy: true,
   reject_if: :all_blank

  validate :course_not_repeated

  scope :course_results_by_course, -> (course_id) {
    where('academico_courses_id = ?', course_id)
  }

  private

  def course_not_repeated
    courses = Academico::CourseResult.course_results_by_course(self.academico_courses_id)
    courses = courses.where('id <> ?', self.id) if self.persisted?
    errors.add(:base, 'Ya existen resultados guardados para este curso') if courses.present?
  end
end

app/models/academico/course_schedulle.rb
class Academico::CourseSchedulle < ApplicationRecord
  has_many :academico_courses, :class_name => "Academico::Course",
    :inverse_of => :academico_course_schedulle, foreign_key: "academico_course_schedulles_id"
  def status
    self.disabled ? "Deshabilitado" : "Habilitado"
  end
  def printable_schedulle
    "#{self.begins.strftime('%H:%M %p')} - #{self.ends.strftime('%H:%M %p')}"
  end

  scope :disableds, -> { where('disabled = true')}
  scope :enableds, -> { where('disabled = false')}
end

app/models/academico/course_status.rb
class Academico::CourseStatus < ApplicationRecord
  has_many :academico_courses, :class_name => "Academico::Course",
		foreign_key: "academico_course_status_id", :inverse_of => :academico_course_status
  REGISTRATION = 1
  ON_GOING = 2
  FINISHED = 3
end

app/views/academico/teacher_attendances/_form.html.erb
<%= form_for(academico_teacher_attendance, html: {:class=>"form-horizontal form-label-left", :novalidate => nil}) do |f| %>
  <% if academico_teacher_attendance.errors.any? %>
    <div id="error_explanation" class="alert-danger">
      <h2><%= pluralize(academico_teacher_attendance.errors.count, "error") %> prohibited this schedulle from being saved:</h2>

      <ul>
        <% academico_teacher_attendance.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="item form-group">
    <%= f.label :academico_courses_id, :class=>"control-label col-md-3 col-sm-3 col-xs-12" do %>
    Curso <span class="required">*
    <%end%>
    <div class="col-md-6 col-sm-6 col-xs-12">
      <% if f.object.new_record? %>
        <%= f.collection_select :academico_courses_id, Academico::Course.all, :id, :description_of_the_course, { include_blank: true}, {:class=>"select2_single form-control", :tabindex=>"-1", :required=>"required", style: "width: 100%;"} %>
      <% else %>
        <%= f.object.academico_course.description_of_the_course %>
      <% end %>
    </div>
  </div>
  <div class="item form-group">
    <%= f.label :academico_staffs_id, :class=>"control-label col-md-3 col-sm-3 col-xs-12" do %>
    Profesor <span class="required">*
    <%end%>
    <div class="col-md-6 col-sm-6 col-xs-12">
      <% if f.object.new_record? %>
        <%= f.collection_select :academico_staffs_id, Academico::Staff.all, :id, :display_name, { include_blank: true}, {:class=>"select2_single form-control", :tabindex=>"-1", :required=>"required", style: "width: 100%;"} %>
      <% else %>
        <%= f.object.academico_staff.display_name %>
      <% end %>
    </div>
  </div>

  <div class="item form-group">
    <div class="col-md-9 col-sm-10 col-xs-12">
      <br>
      <% if f.object.academico_teacher_attendance_details.empty? %>
        <span class="text-warning bg-warning">No hay sesiones asociadas en el temario o no existe un temario para el curso
        <% if f.object.persisted? && defined?(@temary) %>Verifique la información del <%= link_to 'temario', academico_temary_path(@temary) %>
        <% elsif @academico_teacher_attendance.try(:academico_course).present? %>
          Verifique si el docente tiene temario en el <%= link_to 'curso', edit_academico_course_path(@academico_teacher_attendance.try(:academico_course)) %>
        <% end %>
        </span>
      <% else %>
      <div id="academico_teacher_attendance_details">
        <%= f.fields_for :academico_teacher_attendance_details do |f2| %>
          <div class="clearfix child">
            <div class="panel panel-default">
              <div class="panel-body">
                <div class="row">
                  <div class="control-group">

                    <%= f2.hidden_field :id %>
                    <%= f2.hidden_field :academico_teacher_attendances_id %>
                    <%= f2.hidden_field :academico_sessions_id %>
                    <div class="col-md-2 col-sm-2 col-xs-2 text-right">
                      <%= f2.check_box :marked, :class => 'js-switch' %>
                    </div>
                    <div class="col-md-6 col-sm-6 col-xs-10">
                      <span class="form-group form-control">
                        <%= f2.object.academico_session.topic %>
                      </span>
                    </div>
                    <fieldset class="col-md-4 col-sm-4 col-xs-12">
                      <div class="control-group">
                        <div class="controls">
                          <div class="xdisplay_inputx form-group has-feedback">
                            <%= f2.text_field :schedulle, :value => f2.object.formatted_date(:schedulle), :class=>"form-control field_datepicker", :required=>"required", :placeholder=>"dd/mm/yyyy"%>
                            <span class="form-control-feedback fa fa-calendar-o right" aria-hidden="true"></span>
                          </div>
                        </div>
                      </div >
                    </fieldset>

                  </div>
                </div>
              </div>
            </div>

        <% end %>
      </div>
      <% end %>
    </div>
  </div>

  <div class="form-group">
    <div class="col-md-6 col-md-offset-3">
      <%=link_to("Cancelar", academico_teacher_attendances_path, :class=>"btn btn-primary")%>
      <%= submit_tag 'Guardar', class: "btn btn-success", id: "send", data: {disable_with: "Enviando..." } %>
    </div>
  </div>
<% end %>

app/views/academico/teacher_attendances/edit.html.erb
<div class="right_col" role="main">
  <div class="">
    <div class="row">
      <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
          <div class="x_title">
            <h2>Editar asistencia docente</h2>
            <div class="clearfix"></div>
          </div>
          <div class="x_content">
            <%= render "shared/alert" %>
            <%= render 'form', academico_teacher_attendance: @academico_teacher_attendance %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/academico/teacher_attendances/index.html.erb
<div class="right_col" role="main">
  <div class="">

    <div class="clearfix"></div>

    <div class="row">

      <div class="clearfix"></div>

      <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
          <div class="x_title">
            <h2>Registros de asistencia de docentes</h2>
            <ul class="nav navbar-right panel_toolbox panel_button">
              <li>
                <%= link_to(content_tag(:i, nil, :class=>"fa  fa-plus"),new_academico_teacher_attendance_path, :"data-toggle"=>"tooltip", :"data-placement"=>"top", :title=>"", :rel=>"nofollow", :"data-original-title"=>"Nuevo")%>
              </li>
            </ul>
            <div class="clearfix"></div>
          </div>

          <div class="x_content">
            <% if notice.present?%>
              <div class="alert alert-success">
                <a href="#" class="close" data-dismiss="alert" aria-label="close" title="close">×</a>
                <%= notice %>
              </div>
            <% end %>
            <div class="table-responsive">
              <%= form_tag destroy_multiple_academico_teacher_attendances_path, method: :delete, data: { confirm: "Are you sure?"}, :class=>"multi_delete_form" do %>
                <table class="table table-striped jambo_table bulk_action">
                  <thead>
                    <tr class="headings">
                      <th>
                        <input type="checkbox" id="check-all" class="flat">
                      </th>
                      <th class="column-title">Curso</th>
                      <th class="column-title">Docente</th>
                      <th class="column-title">Fecha de creación</th>
                      <th class="column-title">Fecha de actualización</th>
                      <th class="column-title no-link last" colspan="3">Action</th>
                      </th>
                      <th class="bulk-actions" colspan="7">
                        <a type="button" id="delete_records" class="antoo submit-form" style="color:#fff; font-weight:500; cursor:pointer">Eliminar ( <span class="action-cnt"> </span> ) <i class="fa fa-trash-o"></i></button>
                      </th>
                    </tr>
                  </thead>

                  <tbody>
                    <% @academico_teacher_attendances.each_with_index do |academico_teacher_attendance, index| %>
                      <tr class="<%= index.odd? ? 'odd' : 'even'%> pointer">
                        <td class="center">
                                    <input type="checkbox" name="academico_teacher_attendance_ids[]" id="academico_teacher_attendance_id_<%=academico_teacher_attendance.id%>" value="<%=academico_teacher_attendance.id%>" class="flat deletable">
                              </td>

                        <td><%= academico_teacher_attendance.academico_course.description_of_the_course %></td>
                        <td><%= academico_teacher_attendance.academico_staff.display_name %></td>
                        <td><%= academico_teacher_attendance.created_at.strftime('%d-%m-%Y') %></td>
                        <td><%= academico_teacher_attendance.updated_at.strftime('%d-%m-%Y') %></td>

                        <td class=" last">
                          <% if check_permission('show', academico_teacher_attendance) %>
                            <%= link_to content_tag(:i,nil,:class=>"fa fa-search"), academico_teacher_attendance %>
                          <% end %>
                        </td>
                        <td class=" last">
                          <% if check_permission('edit', academico_teacher_attendance) %>
                            <%= link_to content_tag(:i,nil,:class=>"fa fa-pencil"), edit_academico_teacher_attendance_path(academico_teacher_attendance) %>
                          <% end %>
                        </td>
                        <td class=" last">
                          <% if check_permission('destroy', academico_teacher_attendance) %>
                            <%= link_to content_tag(:i,nil,:class=>"fa fa-trash-o"), academico_teacher_attendance, method: :delete, data: { confirm: 'Are you sure?' } %>
                          <% end %>
                        </td>
                      </tr>
                    <% end %>
                  </tbody>

                </table>
              <%end%>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/academico/teacher_attendances/new.html.erb
<div class="right_col" role="main">
  <div class="">
    <div class="row">
      <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
          <div class="x_title">
            <h2>Nuevo registro de asistencias</h2>
            <div class="clearfix"></div>
          </div>
          <div class="x_content">
            <%= render "shared/alert" %>
            <%= render 'form', academico_teacher_attendance: @academico_teacher_attendance %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/academico/teacher_attendances/show.html.erb
<div class="right_col" role="main" style="min-height: 1053px;">
  <div class="">
    <div class="page-title">
      <div class="title_left">
        <h3>Asistencia docente</h3>
      </div>
    </div>

    <div class="clearfix"></div>

    <div class="row">
      <div class="col-md-12">

        <div class="x_panel">

          <div class="x_content">
            <% if notice.present?%>
              <div class="alert alert-success">
                <a href="#" class="close" data-dismiss="alert" aria-label="close" title="close">×</a>
                <%= notice %>
              </div>
            <% end %>
            <div class="col-md-8 col-lg-8 col-sm-7">
              <!-- blockquote -->
              <blockquote>

                <h2>Curso:</h2>
                <h4><%= @academico_teacher_attendance.academico_course.description_of_the_course %></h4>
              </blockquote>

              <blockquote>

                <h2>Profesor:</h2>
                <h4><%= @academico_teacher_attendance.academico_staff.display_name %></h4>
              </blockquote>

              <blockquote class="blockquote-reverse">

                  <%= link_to 'Editar', edit_academico_teacher_attendance_path(@academico_teacher_attendance), :class=>"btn btn-primary" %>
                  <%= link_to 'Atrás', academico_teacher_attendances_path, :class=>"btn btn-success" %>

              </blockquote>
            </div>

          </div>
        </div>
      </div>
    </div>
  </div>
</div>